import type { Metadata } from "next";
import ProfileCard from "@/app/components/ProfileCard";
import Sidebar from "@/app/components/Sidebar";
import { redirect } from "next/navigation";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const authToken = cookieStore.get("authToken")?.value;
  if (!authToken) {
    redirect("/login");
  }
  return (
    <div className="flex flex-col md:flex-row">
      <div className="py-6 w-full md:w-[20%] bg-[#131415] flex flex-col items-center">
        <ProfileCard />
        <Sidebar />
      </div>
      <div className="w-full md:w-[80%] bg-black text-white">{children}</div>
    </div>
  );
}
