import type { Metadata } from "next";
import ProfileCard from "@/app/components/ProfileCard";
import Sidebar from "@/app/components/Sidebar"; // new client component
export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex flex-col md:flex-row">
      <div className="py-6 w-full md:w-[20%] bg-[#131415] flex flex-col items-center">
        <ProfileCard />
        <Sidebar />
      </div>
      <div className="w-full md:w-[80%] bg-black text-white">{children}</div>
    </div>
  );
}
